# Generated by Django 3.2.8 on 2021-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True, max_length=10)),
                ('domains', models.TextField(blank=True, default=None, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('description', models.TextField()),
            ],
        ),
    ]
